[package]
name = "module_1"
version = "0.1.0"
edition = "2021"


[dependencies.windows]
version = "0.28.0"
features = [
"Win32_Foundation",
"Win32_System_LibraryLoader",
"Win32_UI_WindowsAndMessaging",
"Win32_Graphics_Gdi",
]